Try to use with out conda

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -1,4 +1,4 @@
-name: Python Package using Conda
+name: Python Package without Conda
 
 on: [push]
 
@@ -19,68 +19,52 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
-    strategy:
-      max-parallel: 5
 
     steps:
     - uses: actions/checkout@v4
 
-    - name: Set up Miniconda
-      uses: conda-incubator/setup-miniconda@v3
+    - name: Set up Python
+      uses: actions/setup-python@v4
       with:
-        auto-update-conda: true
-        python-version: "3.12.3"
-        environment-file: ""  # No usamos environment.yml
-
-    - name: Create and activate Conda environment
-      run: |
-        conda create --name myenv python=3.10 -y
-        echo "CONDA_ENV=myenv" >> $GITHUB_ENV
+        python-version: "3.10"
 
     - name: Install dependencies
       run: |
-        source $(conda info --base)/etc/profile.d/conda.sh
-        conda activate $CONDA_ENV
-        conda install -y flake8 pytest pytest-cov psycopg2
-        pip install --upgrade pip
+        python -m pip install --upgrade pip
         pip install -r requirements.txt
-        pip install pytest pytest-cov  # Install pytest and coverage plugins
+        pip install flake8 pytest pytest-cov
 
     - name: Lint with flake8
       run: |
-        source $(conda info --base)/etc/profile.d/conda.sh
-        conda activate $CONDA_ENV
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
     - name: Run Alembic migrations
-      run: alembic upgrade head
-      
+      run: |
+        alembic upgrade head
 
     - name: Test with pytest and collect coverage
       run: |
-        source $(conda info --base)/etc/profile.d/conda.sh
-        conda activate $CONDA_ENV
         pytest --cov=./ --cov-report=xml
 
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v5
       with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: backend/coverage-go.out
-          fail_ci_if_error: true
-          verbose: true
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: backend/coverage-go.out
+        fail_ci_if_error: true
+        verbose: true
 
     - name: Check Coverage Percentage
       run: |
-            echo "📊 Checking minimum required coverage..."
-            COVERAGE=$(pytest --cov=./ --cov-report=term | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
-            echo "Coverage obtained: $COVERAGE%"
-            if (( $(echo "$COVERAGE >= 75" | bc -l) )); then
-              echo "❌ Error: Coverage is 75% or more. Deployment is blocked."
-              exit 1
-            fi
-            echo "✅ Coverage is below 75%. Continuing."
+        echo "📊 Checking minimum required coverage..."
+        COVERAGE=$(pytest --cov=./ --cov-report=term | grep "TOTAL" | awk '{print $NF}' | sed 's/%//')
+        echo "Coverage obtained: $COVERAGE%"
+        if (( $(echo "$COVERAGE >= 75" | bc -l) )); then
+          echo "❌ Error: Coverage is 75% or more. Deployment is blocked."
+          exit 1
+        fi
+        echo "✅ Coverage is below 75%. Continuing."
 
     - name: Deploy to production
       if: github.ref == 'refs/heads/main' && success()
